/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package dinasour;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.Arrays;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test
    public void testFound() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
       assertTrue(App.fonksiyon(array, 4,0));
     }
 
     @Test
     public void testNotFound() {
       ArrayList<Integer> array = new ArrayList<>(Arrays.asList(1, 2, 3, 4));
       assertFalse(App.fonksiyon(array, 5, 0));
     }
 
     @Test
     public void testEmptyArray() {
       ArrayList<Integer> array = new ArrayList<>();
       assertFalse(App.fonksiyon(array, 1, 0));
     }
 
     @Test
     public void testNull() {
       assertFalse(App.fonksiyon(null, 1, 0));
     }
 
}
